name: Jest Coverage Action
description: Comments PR with Jest Coverage stats
author: Insider Development
branding:
  icon: percent
  color: green
inputs:
  github-token:
    description: Github token
    required: true
  lcov-file:
    description: The location of the lcov.info file
    required: false
runs:
  using: node12
  main: dist/main.js